spring:
  application:
    name: turbin
    
server:
  port: 5001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
#turbine:
  #app-config: order-service, feign  #需要聚合监控数据的服务器
  #cluster-name-expression: new String("default")  #聚合监控的起名格式

#修改 turbine 项目，聚合 zuul 服务实例
turbine:
  app-config: order-service, zuul
  cluster-name-expression: new String("default")